# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v1
    - name: Get swift version
      run: swift --version # Swift 5.9.2
    - name: list files
      run: ls
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
