name: "CI/CD"

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"  

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: build xcode
        run: xcodebuild -scheme PokerSen
